### ISSUE TITLE
Install eMMC rk3328

### ISSUE THREAD

**Issue by 150balbes** [150balbes/LibreELEC.tv#23]
Hi @mo123
Try a few tests. Connect via SSH and run the manual backup script (ddbr_backup), the result throw me. Just manually try to run the installation script (install2emmc.sh) and the result send to me. Try to download my finished image for rk3328 and to do so in the manually  backup and installation.

**Comment by 150balbes** [comment]
@mo123

I took your last image from that description.
https://forum.libreelec.tv/thread/12151-feedback-for-test-build-libreelec-rk3328/?postID=105418#post105418

Checked the script of the backup. Started from GUI command of creation of a copy, in 24 minutes the system automatically was switched off and the full copy of eMMC on MVR9 was created. After that, I replaced the script in /LIBREELEC with this one
https://github.com/150balbes/LibreELEC.tv/blob/Amlogic-Leia-4.x/projects/Rockchip/devices/RK3328/packages/rockchip-autoscript/instboot/install2emmc.sh

Started from GUI installation in eMMC and the system was normally established in eMMC. I checked the launch of LE from eMMC, everything works correctly.

**Comment by mo123** [comment]
Hi

I got it working now.

Seems I didn't wait the full 24 minutes.

Do you know what boot.img, partitions etc. are used to install to emmc?
Then I can perhaps build an update.img to flash with AndroidTool on a PC for RK3328 devices to install directly to emmc, overwriting Android.

**Comment by 150balbes** [comment]
The kernel in LE for rk3328 cannot work with Android partitions. The eMMC installation uses the usual MBR partition table and two partitions in the eMMC, exactly the same as on the SD card (but with other labels, that would not be a problem for the internal and external version). So I doubt it is possible to build an image to use USB Burn Tool because there are no Android partitions at all.
