### ISSUE TITLE
Do you have the arm architecture compiled?

### ISSUE THREAD

**Issue by kero990** [150balbes/LibreELEC.tv#40]
Thank you for your work. There are a lot of people in China who use your system to make their TV box more useful, not limited to the weak android.
I visited your yandex network disk, your compiled system seems to be aarch64 architecture, which makes many libreelec plugins not working properly. Do you have the arm architecture compiled?
I am sorry to open an new issue for this reason only, but I really don't know how to contact you and will not bother you. Sorry.

The above is from Google Translate, I hope you can understand. If the language is offensive, please blame Google.

**Comment by 150balbes** [comment]
> compiled system seems to be aarch64 architecture

What systems are we talking about ?
