### ISSUE TITLE
Missing GLESv1 support, how can I add it?

### ISSUE THREAD

**Issue by kero990** [150balbes/LibreELEC.tv#41]
I started with you compiled image on my device, but the retroarch plugin and the like could not be started, showing the missing libGLESv1_CM.so.1 file.

> /storage/.kodi/addons/script.emuelec.Amlogic.launcher/bin/emulationstation: error while loading shared libraries: libGLESv1_CM.so.1: cannot open shared object file: No such file or directory

However, I found that I can't add these libraries without recompiling. I can't mount the SYSTEM file on my debian system, nor can I add it via winscp when libreelec starts. At this time, /usr/lib is read-only.

There may be other files missing, but the retroarch startup to GLESv1 is missing, so I can't know what is missing.

Is there any way to complete these files without recompiling libreelec? Maybe my linux level is too bad.

**Comment by kero990** [comment]
The kodi plugin I am using is this:

> https://github.com/shantigilbert/EmuELEC/releases/tag/addon_v2.5

It was originally based on CoreELEC, so I don't know what is missing on your libreelec.
My device is special. Currently, only armbian and libreelec that you compile can run, so I can't try other systems and I can't compile them myself. sorry to disturb you.

**Comment by 150balbes** [comment]
My versions are based on a different kernel and older versions of the libraries will not work on it.

**Comment by kero990** [comment]
I filled in the missing lib in the plugin's lib folder according to the plugin's log, but I don't know if the version is compliant. At least the log will not prompt me that the version of lib is wrong. If the lakka library is copied, the version will not be high enough.Now the log does not prompt the lack of lib, but the error is as follows:

```
sh: setterm: not found
sh: setterm: not found
lvl0: 	Error creating SDL window!
	mali-fbdev: Can't create EGL window surface
lvl0: 	Renderer failed to initialize!
lvl0: 	Window failed to initialize!
```

I can still understand the lack of the library. I can't understand this error. Google can't help me.
I just want to run retroarch+emulationstation on your libreelec, because only your system can run on my device.

**Comment by kero990** [comment]
In addition, where is the setting that Kodi starts when the device boots? Is there a script similar to auotstart.sh to control? So where is the setting to restart kodi after kodi crashes? Is this setting or script related to the inability of the program plugin to run?

**Comment by kero990** [comment]
I am sorry for so many problems, this is just discovered.
I downloaded the latest image LibreELEC-AMLGX.arm-9.80-devel-20190820163006-07b919f-s905.img.gz, it seems to be the arm architecture, but my unname has got aarch64, what is the architecture of this libreelec?
```
LibreELEC:~ # uname -a
Linux LibreELEC 5.2.1 #1 SMP Tue Aug 20 15:22:12 MSK 2019 aarch64 GNU/Linux

```

**Comment by 150balbes** [comment]
> I can still understand the lack of the library. I can't understand this error. Google can't help me.
> I just want to run retroarch+emulationstation on your libreelec, because only your system can run on my device.

Once again, the new core for AMLGX will not run the old versions of the mali libraries, it uses a completely different driver Lima|Panfrost.



> In addition, where is the setting that Kodi starts when the device boots? Is there a script similar to auotstart.sh to control? So where is the setting to restart kodi after kodi crashes? Is this setting or script related to the inability of the program plugin to run?

The description of how to run and configure KODI LE is in the WiKi for LE and KODI.



> I am sorry for so many problems, this is just discovered.
> I downloaded the latest image LibreELEC-AMLGX.arm-9.80-devel-20190820163006-07b919f-s905.img.gz, it seems to be the arm architecture, but my unname has got aarch64, what is the architecture of this libreelec?

kernel - aarch64 (64 bit)
all system LE -  arm (32 bit)

**Comment by kero990** [comment]
Then what you said "old version", such as libGLESv1-1.1.0-1+b1, means that the v1 version of libgles can not be used, or the version number of 1.1.0?
I guess the former, then that means that all programs that rely on the old libGLESv1 will not run on your new kernel unless they update the program.
Am I correct this time?
